# Generated by Django 5.2.8 on 2025-11-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_priority_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'muhum'), ('M', 'urtacha'), ('H', 'shartmas')], default='M', max_length=1),
        ),
    ]
